# Generated by Django 3.2 on 2023-03-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0002_alter_assignment_course'),
        ('widget_Calendar', '0002_event_location_delete_indexcard_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='Assignments.course'),
        ),
    ]
