# Generated by Django 3.2 on 2023-03-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_Calendar', '0003_alter_event_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='target_datetime',
            field=models.DateTimeField(),
        ),
    ]
