# Generated by Django 3.2 on 2023-05-11 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_widgetuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetuser',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='Dashboard.department'),
        ),
    ]
